### ISSUE TITLE
Add custom options to default components

### ISSUE THREAD

**Issue by willybrauner** [agentejo/LayoutComponents#7]
Is there a way to add a custom option to default component like "Grid" ? I will need to add a select field to it. 

<img width="1261" alt="Capture d’écran 2020-06-03 à 15 30 39" src="https://user-images.githubusercontent.com/7604357/83642509-37aa7800-a5af-11ea-9a46-21d39d23b2b3.png">

Thanks!

**Comment by DanielWahl** [comment]
Hey,
Is this solved? I also need the possibility to change default components.
