### ISSUE TITLE
Missing license file - MIT?

### ISSUE THREAD

**Issue by raffaelj** [agentejo/LayoutComponents#8]
Is this addon licensed under MIT, like all other cockpit sources?

I used some code from this addon to override the settings page in the [BlockEditor addon](https://github.com/raffaelj/cockpit_BlockEditor) to provide more options. While updating the readme to list the credits I noticed the missing license file.

**Comment by aheinze** [comment]
Yes, if not other mentioned, everything is under the MIT license

**Comment by raffaelj** [comment]
OK. Good to know.
